@JWT_A =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhQHRlc3QuY29tIiwiaWF0IjoxNzY3NzAyNjI0LCJleHAiOjE3Njc3MDYyMjR9.8mVnpHB4SkFF000Vhcy61Q6oD07jgplGhdHgBocdVsQ
@NOTE_ID = 1
@JWT_B = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiQHRlc3QuY29tIiwiaWF0IjoxNzY3NzAxODk1LCJleHAiOjE3Njc3MDU0OTV9.xAAc-X3w-orUXnYw7MUp7WVlPWBZRzImoj8rxFgBt_s
### Register User A
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "email": "a@test.com",
  "password": "password"
}

### Login User A
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "a@test.com",
  "password": "password"
}

### Me (User A)
GET http://localhost:8081/me
Authorization: Bearer {{JWT_A}}

### Create note (User A)
POST http://localhost:8081/notes
Authorization: Bearer {{JWT_A}}
Content-Type: text/plain

note from user A

### Register User B
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "email": "b@test.com",
  "password": "password"
}

### Login User B
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "b@test.com",
  "password": "password"
}

### Ownership test
GET http://localhost:8081/notes/{{NOTE_ID}}
Authorization: Bearer {{JWT_A}}