CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE folders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ(6)                          NOT NULL,
    updated_at TIMESTAMPTZ(6)                          NOT NULL,
    name       VARCHAR(255),
    owner_id   BIGINT                                  NOT NULL,
    deleted_at TIMESTAMPTZ(6),
    CONSTRAINT pk_folders PRIMARY KEY (id),
    CONSTRAINT fk_folders_on_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uc_tag_name UNIQUE (name)
);

CREATE TABLE note
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMPTZ(6)                          NOT NULL,
    updated_at         TIMESTAMPTZ(6)                          NOT NULL,
    deleted_at         TIMESTAMPTZ(6),
    cascade_deleted_at TIMESTAMPTZ(6),
    content            VARCHAR(255),
    owner_id           BIGINT                                  NOT NULL,
    folder_id          BIGINT                                  NOT NULL,
    visibility         VARCHAR(255),
    CONSTRAINT pk_note PRIMARY KEY (id),
    CONSTRAINT fk_note_on_owner  FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_note_on_folder FOREIGN KEY (folder_id) REFERENCES folders (id),
    CONSTRAINT note_visibility_check CHECK (visibility IN ('PRIVATE', 'SHARED_LINK'))
);

CREATE TABLE note_tags
(
    note_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_note_tags PRIMARY KEY (note_id, tag_id),
    CONSTRAINT fk_note_tags_on_note FOREIGN KEY (note_id) REFERENCES note (id),
    CONSTRAINT fk_note_tags_on_tag  FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE shared_link
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    note_id    BIGINT                                  NOT NULL,
    creator_id BIGINT                                  NOT NULL,
    expires_at TIMESTAMPTZ(6),
    revoked_at TIMESTAMPTZ(6),
    CONSTRAINT pk_sharedlink PRIMARY KEY (id),
    CONSTRAINT uc_sharedlink_token UNIQUE (token),
    CONSTRAINT fk_sharedlink_on_creator FOREIGN KEY (creator_id) REFERENCES users (id),
    CONSTRAINT fk_sharedlink_on_note    FOREIGN KEY (note_id) REFERENCES note (id)
);

CREATE TABLE shared_link_actions
(
    shared_link_id BIGINT NOT NULL,
    action         VARCHAR(255),
    CONSTRAINT fk_shared_link_actions_on_shared_link FOREIGN KEY (shared_link_id) REFERENCES shared_link (id),
    CONSTRAINT shared_link_actions_action_check CHECK (action IN ('READ', 'UPDATE'))
    );

CREATE TABLE revoked_token
(
    jti        VARCHAR(255) NOT NULL,
    revoked_at TIMESTAMPTZ(6),
    CONSTRAINT pk_revokedtoken PRIMARY KEY (jti)
);

CREATE TABLE idempotent_actions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_key VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMPTZ(6)                          NOT NULL,
    CONSTRAINT pk_idempotent_actions PRIMARY KEY (id),
    CONSTRAINT uc_idempotent_actions_action_key UNIQUE (action_key)
);

CREATE TABLE job_failures
(
    id            UUID NOT NULL,
    job_type      VARCHAR(255),
    action_key    VARCHAR(255),
    payload       VARCHAR(255),
    error_message VARCHAR(255),
    failed_at     TIMESTAMPTZ(6),
    CONSTRAINT pk_job_failures PRIMARY KEY (id)
);